apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: jrg4b1uut-go 
  janus-idp.io/tekton: jrg4b1uut-go
  backstage.io/kubernetes-id: jrg4b1uut-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jrg4b1uut-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml