apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jrg4b1uut-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jrg4b1uut-go 
  name: jrg4b1uut-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jrg4b1uut-go 
